from __future__ import annotations

from collections import Counter
from typing import Any, Mapping


SCHEMA = "nexus.representation-source-evidence.v1"

# Reviewed public, first-party documentation. These references support only the
# specific claims named below; they are not blanket authority for a particular
# CSV's chart type, export settings, timestamp field semantics, or volume field.
SOURCES = (
    {
        "source_id": "tradingview.timeframe-spec",
        "publisher": "TradingView",
        "title": "Pine Script Concepts / Timeframes",
        "url": "https://www.tradingview.com/pine-script-docs/concepts/timeframes/",
        "supports": [
            "timeframe string syntax",
            "seconds use S postfix",
            "minutes use no postfix",
            "240 means 240 minutes",
        ],
        "authoritative_first_party": True,
    },
    {
        "source_id": "tradingview.time-semantics",
        "publisher": "TradingView",
        "title": "Pine Script Concepts / Time",
        "url": "https://www.tradingview.com/pine-script-docs/concepts/time/",
        "supports": [
            "Pine time variable is current bar opening UNIX timestamp",
            "time_close is current bar closing UNIX timestamp",
            "non-time-based chart bars can span irregular intervals",
        ],
        "authoritative_first_party": True,
    },
    {
        "source_id": "tradingview.chart-export",
        "publisher": "TradingView",
        "title": "How to export chart data",
        "url": "https://www.tradingview.com/support/solutions/43000537255-how-to-export-chart-data/",
        "supports": [
            "chart data can be exported as CSV",
            "exported data reflects chart data that has been loaded",
        ],
        "authoritative_first_party": True,
    },
)


def tradingview_timeframe_seconds(value: str | None) -> int | None:
    """Return fixed seconds for TradingView timeframe strings when well-defined.

    Month timeframes deliberately return None because calendar months have no
    fixed duration in seconds. This parser is intentionally narrower than a
    generic filename parser: its job is to encode the reviewed first-party
    TradingView timeframe specification.
    """
    if not value:
        return None
    value = str(value).strip().upper()
    if not value:
        return None

    if value.endswith("S"):
        multiplier = value[:-1]
        if multiplier.isdigit() and int(multiplier) in {1, 5, 10, 15, 30, 45}:
            return int(multiplier)
        return None

    if value.endswith("D"):
        multiplier = value[:-1] or "1"
        if multiplier.isdigit() and 1 <= int(multiplier) <= 365:
            return int(multiplier) * 86_400
        return None

    if value.endswith("W"):
        multiplier = value[:-1] or "1"
        if multiplier.isdigit() and 1 <= int(multiplier) <= 52:
            return int(multiplier) * 7 * 86_400
        return None

    if value.endswith("M"):
        # Calendar months are valid TradingView timeframe strings but are not a
        # fixed nanosecond cadence and therefore cannot be compared this way.
        multiplier = value[:-1] or "1"
        return None if multiplier.isdigit() and 1 <= int(multiplier) <= 12 else None

    if value.isdigit() and 1 <= int(value) <= 1440:
        return int(value) * 60
    return None


def _comparison(claim_seconds: int | None, observed_cadence_ns: int | None) -> str:
    if claim_seconds is None or not observed_cadence_ns:
        return "UNRESOLVED"
    expected_ns = claim_seconds * 1_000_000_000
    if int(observed_cadence_ns) == expected_ns:
        return "EXACT_CADENCE_MATCH"
    if int(observed_cadence_ns) < expected_ns:
        return "OBSERVED_FASTER_THAN_STANDARD_TIMEFRAME_CLAIM"
    return "OBSERVED_SLOWER_THAN_STANDARD_TIMEFRAME_CLAIM"


def build_representation_source_evidence(review_triage: Mapping[str, Any]) -> dict[str, Any]:
    """Attach reviewed source-level semantics to P0 representation clusters.

    This does *not* resolve a stream's representation. It proves only what the
    reviewed documentation supports: the meaning of a TradingView timeframe
    string and general TradingView bar-time/export behavior. In particular,
    this function refuses to infer that a filename was generated by TradingView,
    that the CSV ``time`` column necessarily maps to Pine ``time``, or that the
    chart was a standard time-based chart.
    """
    clusters = [c for c in review_triage.get("clusters", []) if isinstance(c, Mapping)]
    comparison_counts: Counter[str] = Counter()
    stream_comparison_counts: Counter[str] = Counter()
    evidence_rows: list[dict[str, Any]] = []

    for cluster in clusters:
        claim = str(cluster.get("filename_claim") or "")
        claim_seconds = tradingview_timeframe_seconds(claim)
        observed_ns = cluster.get("observed_cadence_ns")
        comparison = _comparison(claim_seconds, int(observed_ns) if observed_ns else None)
        count = int(cluster.get("stream_count") or 0)
        comparison_counts[comparison] += 1
        stream_comparison_counts[comparison] += count

        standard_compatible: bool | None
        if comparison == "EXACT_CADENCE_MATCH":
            standard_compatible = True
        elif comparison in {
            "OBSERVED_FASTER_THAN_STANDARD_TIMEFRAME_CLAIM",
            "OBSERVED_SLOWER_THAN_STANDARD_TIMEFRAME_CLAIM",
        }:
            standard_compatible = False
        else:
            standard_compatible = None

        evidence_rows.append({
            "triage_class": str(cluster.get("triage_class") or ""),
            "venue": str(cluster.get("venue") or "?"),
            "symbols": list(cluster.get("symbols") or []),
            "stream_ids": list(cluster.get("stream_ids") or []),
            "stream_count": count,
            "filename_claim": claim or None,
            "observed_cadence_ns": int(observed_ns) if observed_ns else None,
            "reviewed_timeframe_claim_seconds": claim_seconds,
            "claim_vs_observed": comparison,
            "standard_time_based_cadence_compatible": standard_compatible,
            "source_evidence": {
                "timeframe_string_semantics": "AUTHORITATIVE_SUPPORTED" if claim_seconds is not None else "UNRESOLVED",
                "export_is_loaded_chart_data": "AUTHORITATIVE_SUPPORTED",
                "pine_time_is_bar_open_timestamp": "AUTHORITATIVE_SUPPORTED_GENERAL_RULE",
                "filename_was_generated_from_chart_timeframe": "NOT_DIRECTLY_ATTESTED",
                "csv_time_column_equals_pine_time": "NOT_DIRECTLY_ATTESTED",
                "chart_type_standard_time_based": "NOT_ATTESTED",
                "timezone_session_for_this_export": "NOT_ATTESTED_BY_THESE_SOURCES",
                "volume_semantics_for_this_export": "NOT_ATTESTED_BY_THESE_SOURCES",
            },
            "remaining_p0": True,
            "auto_resolved": False,
            "production_authorized": False,
        })

    evidence_rows.sort(key=lambda x: (-x["stream_count"], x["venue"], str(x["filename_claim"]), x["claim_vs_observed"]))

    exact_streams = stream_comparison_counts.get("EXACT_CADENCE_MATCH", 0)
    incompatible_streams = (
        stream_comparison_counts.get("OBSERVED_FASTER_THAN_STANDARD_TIMEFRAME_CLAIM", 0)
        + stream_comparison_counts.get("OBSERVED_SLOWER_THAN_STANDARD_TIMEFRAME_CLAIM", 0)
    )
    return {
        "schema": SCHEMA,
        "sources": list(SOURCES),
        "cluster_count": len(evidence_rows),
        "p0_stream_count": sum(int(x["stream_count"]) for x in evidence_rows),
        "comparison_cluster_counts": dict(sorted(comparison_counts.items())),
        "comparison_stream_counts": dict(sorted(stream_comparison_counts.items())),
        "standard_timeframe_cadence_compatible_stream_count": exact_streams,
        "standard_timeframe_cadence_incompatible_stream_count": incompatible_streams,
        "clusters": evidence_rows,
        "authoritative_dimensions_resolved": [
            "TradingView timeframe-string syntax",
            "general TradingView Pine bar-open time semantics",
            "general TradingView chart-data export behavior",
        ],
        "dimensions_still_requiring_export_specific_evidence": [
            "filename-to-chart-timeframe provenance",
            "CSV time-column mapping to Pine time/time_close/event completion",
            "chart type (standard time-based vs non-standard/derived)",
            "export-specific timezone/session setting",
            "export-specific volume semantics when volume is present",
        ],
        "auto_resolved_count": 0,
        "production_authorized": False,
    }
